version: 2.1
orbs:
  node: circleci/node@3.0.0
  jobs:
    build-and-test:
      executor:
        name: node/default
      steps:
        - checkout
        - node/with-cache:
            steps:
              - run: npm install
              - run: npm run init
              - run: npm run lint
              - run: npm run build
  workflows:
    build-test-deploy:
      jobs:
        - build-and-test
        - deploy-functions:
            requires:
              - build-and-test
            filters:
              branches:
                only:
                  - master

