---
jobs:
  test:
    docker:
      - image: circleci/node:8.6.0
      - image: cassandra:3.11
    resource_class: large
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
      - run: npm run lint
      - run: npm test
      - store_artifacts:
          path: .coverage
  version: 2
  test_and_build:
    jobs:
      - test
